### ISSUE TITLE
Type error in NodeJS

### ISSUE THREAD

**Issue by Pusherman2** [FishRoyal/futures-binance-bot#4]
Hi there, very interesting bot. However, I got the following error when running on TestNet:

`/futures-binance-bot/build/Signal.js:10
        if (!("USDT" in symbol))
                     ^

TypeError: Cannot use 'in' operator to search for 'USDT' in TRBUSDT
    at Signal.ifSignalApproach (/futures-binance-bot/build/Signal.js:10:22)
    at User.<anonymous> (/futures-binance-bot/build/User.js:75:97)
    at Generator.next (<anonymous>)
    at futures-binance-bot/build/User.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/futures-binance-bot/build/User.js:4:12)
    at WebsocketClient.<anonymous> (/futures-binance-bot/build/User.js:40:55)
    at WebsocketClient.emit (node:events:390:28)
    at WebsocketClient.onWsMessage (/futures-binance-bot/node_modules/binance/lib/websocket-client.js:228:26)
    at WebSocket.ws.onmessage (/futures-binance-bot/node_modules/binance/lib/websocket-client.js:120:38)

Node.js v17.1.0`

Any idea how or why this error pops up for the liquidation stream?

Kind regards.

**Comment by FishRoyal** [comment]
My mistake. It should be symbol.includes("USDT").
Also if you use testnet you can comment 10, 11, 12 lines in Signal class. So you will not have to wait too long for a big signal.
